
export const 
    logo = '/logo',
    cart_icon = '/cart_icon',
    hand_icon = '/hand_icon',
    arrow_icon = '/arrow',
    breadcrum_arrow_icon = '/breadcrum_arrow',
    hero_image = '/hero_image',
    exclusive_image = '/exclusive_image',
    footer_logo = '/logo_big',
    instagram_icon = '/instagram_icon',
    pintester_icon = '/pintester_icon',
    whatsapp_icon = '/whatsapp_icon',
    men_banner = '/banner_mens',
    women_banner = '/banner_women',
    kids_banner = '/banner_kids',
    dropdown_icon = '/dropdown_icon',
    star_icon = '/star_icon',
    star_dull_icon = '/star_dull_icon',
    remove_icon = '/cart_cross_icon',
    nav_dropdown_icon = '/dropdown_icon'